### ISSUE TITLE
orig_atom_fea_len

### ISSUE THREAD

**Issue by xiaowangfeng** [jonathanBalasingham/Periodic-Set-Transformer#4]
Hello, I would like to know why the orig_atom_fea_len you use is 16, while the one used by cgcnn is 92.
How did you choose it?

**Comment by jonathanBalasingham** [comment]
Apologies for the late response. The dimension of 16 consists of 1 dimension dedicated to atoms type and k=15 for nearest neighbor distances. The variable name is a bit of a misnomer, but it is convenient when batching the data.
