### ISSUE TITLE
how you measure your training and testing time

### ISSUE THREAD

**Issue by xiaowangfeng** [jonathanBalasingham/Periodic-Set-Transformer#5]
Hi, I would like to know how you measure your training and testing time. Is it by manual timing?

**Comment by jonathanBalasingham** [comment]
No it is done automatically in python (see lines 80 and 90 of mb.py). Timing is not done when using main.py

**Comment by xiaowangfeng** [comment]
Thank you for your answer, I ran run_jarvis.py. I only got the training time for each epoch, I want to know how to get the total time directly?

**Comment by jonathanBalasingham** [comment]
Ah, there is a bit of inconsistency between mb.py and run_jarvis.py; the training and prediction time is listed in the .csv files that are produced instead of being printed

**Comment by xiaowangfeng** [comment]
Ah, I have found them, thank you.
